Feature/get operation 009: Created GET Operation
at-internship/at-university-api pull request #4
Opened 2020-10-02 19:15 UTC by ErnestoZamora

Created GET Operation

2020-10-02 21:38 UTC, JoseCortes-Agile requested changes

2020-10-02 21:38 UTC, JoseCortes-Agile commented on src/main/java/com/university/university/controller/UniversityController.java
> +import java.util.Optional;
Please remove any Import that is not used

2020-10-02 21:38 UTC, JoseCortes-Agile commented on src/main/java/com/university/university/controller/UniversityController.java
> +		//return "Hello at-university-api";
Please remove commented code, we should deliver clean code

2020-10-02 21:38 UTC, JoseCortes-Agile commented on src/main/java/com/university/university/model/Course.java
> +import org.springframework.stereotype.Indexed;
Remove all the unused imports

2020-10-02 21:38 UTC, JoseCortes-Agile commented on src/main/java/com/university/university/model/Course.java
> +@Data
Please do not use Data annotation it import a lot of classes that we do not use, 
Only use the necessary annotations

2020-10-02 21:38 UTC, JoseCortes-Agile commented on src/main/java/com/university/university/model/Course.java
> +    private String _id;
Id should be String.

2020-10-02 21:38 UTC, JoseCortes-Agile commented on src/main/java/com/university/university/repository/CourseRepository.java
> +import java.util.List;
Remove unused imports

2020-10-02 21:38 UTC, JoseCortes-Agile commented on src/main/java/com/university/university/service/AtUniversityServiceImpl.java
> +        return courses;
Courses variable is not needed, we can return the list directly in Return statement.

2020-10-02 23:11 UTC, JoseCortes-Agile commented
Please pull also develop code into your branch, seems that we have new changes there and resolve conflicts

2020-10-05 16:44 UTC, at-internship requested changes
Verify comments

2020-10-05 16:44 UTC, at-internship commented on src/main/java/com/university/university/controller/UniversityController.java
>  package com.university.university.controller;
please refactor package name to 
package com.agilethought.internship.university.controller;

2020-10-05 16:44 UTC, at-internship commented on src/main/resources/application.properties
> +spring.data.mongodb.uri: mongodb+srv://at-university-api:4gil3th0ught@cluster0.6xlmy.mongodb.net/at-university-db?retryWrites=true&w=majority
This type of sensitive information should not be added here

2020-10-05 17:07 UTC, JoseCortes-Agile commented
I see the PR has conflicts, please solve them, also it has some comments from At-intership, please review them

2020-10-05 19:26 UTC, closed without merging